
us_states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

state2timezone = { 'AK': 'US/Alaska', 'AL': 'US/Central', 
                  'AR': 'US/Central', 'AS': 'US/Samoa', 
                  'AZ': 'US/Mountain', 'CA': 'US/Pacific', 
                  'CO': 'US/Mountain', 'CT': 'US/Eastern', 
                  'DC': 'US/Eastern', 'DE': 'US/Eastern', 
                  'FL': 'US/Eastern', 'GA': 'US/Eastern', 
                  'GU': 'Pacific/Guam', 'HI': 'US/Hawaii', 
                  'IA': 'US/Central', 'ID': 'US/Mountain', 
                  'IL': 'US/Central', 'IN': 'US/Eastern', 
                  'KS': 'US/Central', 'KY': 'US/Eastern', 
                  'LA': 'US/Central', 'MA': 'US/Eastern', 
                  'MD': 'US/Eastern', 'ME': 'US/Eastern', 
                  'MI': 'US/Eastern', 'MN': 'US/Central', 
                  'MO': 'US/Central', 'MP': 'Pacific/Guam', 
                  'MS': 'US/Central', 'MT': 'US/Mountain', 
                  'NC': 'US/Eastern', 'ND': 'US/Central', 
                  'NE': 'US/Central', 'NH': 'US/Eastern', 
                  'NJ': 'US/Eastern', 'NM': 'US/Mountain', 
                  'NV': 'US/Pacific', 'NY': 'US/Eastern', 
                  'OH': 'US/Eastern', 'OK': 'US/Central', 
                  'OR': 'US/Pacific', 'PA': 'US/Eastern', 
                  'PR': 'America/Puerto_Rico', 'RI': 'US/Eastern', 
                  'SC': 'US/Eastern', 'SD': 'US/Central', 
                  'TN': 'US/Central', 'TX': 'US/Central', 
                  'UT': 'US/Mountain', 'VA': 'US/Eastern', 
                  'VI': 'America/Virgin', 'VT': 'US/Eastern', 
                  'WA': 'US/Pacific', 'WI': 'US/Central', 
                  'WV': 'US/Eastern', 'WY': 'US/Mountain', 
                  '' : 'US/Pacific', '--': 'US/Pacific' }


map_us_tz_to_utc = {
    'US/Eastern': -4,
    'US/Pacific': -7,
    'US/Central': -5,
    'US/Mountain': -6,
    'US/Hawaii': -10,
    'US/Alaska': -8
}

